from selenium import webdriver 
from selenium.webdriver.common.keys import Keys
from random_user_agent.user_agent import UserAgent
from random_user_agent.params import SoftwareName, OperatingSystem

def main():
    software_names = [SoftwareName.CHROME.value]
    operating_systems = [OperatingSystem.WINDOWS.value]   
    user_agent_rotator = UserAgent(software_names=software_names, operating_systems=operating_systems, limit=100)
    user_agent = user_agent_rotator.get_user_agents()
    user_agent = user_agent_rotator.get_random_user_agent()

    chromeOptions = webdriver.ChromeOptions()
    chromeOptions.add_argument("--headless")
    chromeOptions.add_argument("user-agent="+str(user_agent))
    chromeOptions.add_argument("--disable-extensions")
    chromeOptions.add_argument("test-type")
    chromeOptions.add_argument("--log-level=3")
    chromeOptions.add_argument("--test-type")
    chromeOptions.add_argument("--disable-gpu")
    chromeOptions.add_argument("--no-first-run")
    chromeOptions.add_argument("--no-default-browser-check")
    chromeOptions.add_argument("--ignore-certificate-errors")
    chromeOptions.add_argument("--start-maximized")
    driver = webdriver.Chrome(options=chromeOptions)
    driver.get("https://osint.sh/")
    n=int(input("1.Website recon 2.S3 Bucket 3.Network Mapping : "))
    if n==1:
        t=input("Enter your Target Webaddress : ")
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[5]/div/a").click()
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(t)
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("TECHNOLOGY USED")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div").text)
        print("----------------------------------------------------------------------------------------")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[11]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(t) 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("WHOIS INFORMATION")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div").text)
        print("----------------------------------------------------------------------------------------")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click()
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[2]/div/a").click()
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(t)
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("SUBDOMAIN INFORMATION")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[3]").text)
        print("----------------------------------------------------------------------------------------")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click()
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[7]/div/a").click()
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(t)
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("DNS LOOKUP")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[2]/div").text)
        print("----------------------------------------------------------------------------------------")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[3]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(t) 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("DNS HISTORY LOOKUP")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[2]/div").text)
        print("----------------------------------------------------------------------------------------")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[6]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(t) 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("WEB CERTIFICATE INFORMATION")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/table").text)
        print("----------------------------------------------------------------------------------------")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click() 
    elif n==2:
        k=input("Enter Keyword : ")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[1]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/div/div[1]/input").send_keys(k)
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/div/div[3]/button").click()
        print("S3 BUCKET LIST")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[3]/div").text)
        print("----------------------------------------------------------------------------------------")
    elif n==3:
        ip=input("Enter IP address / Website Add : ")
        driver.find_element_by_xpath("/html/body/div[1]/div/nav/div/div/div[1]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section[2]/div/div/div[16]/div/a").click() 
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/input").send_keys(ip)
        driver.find_element_by_xpath("/html/body/div[2]/section/div/div[2]/div/form/button").click()
        print("NETWORK MAPPING")
        print(driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div/div").text)
        print("----------------------------------------------------------------------------------------")
    
if __name__ == '__main__':
    main()